project_id = "rubrttlaitstladaukpd"

[functions.wayback-lookup]
verify_jwt = false

[functions.verify-content]
verify_jwt = false

[functions.detect-controversy]
verify_jwt = false

[functions.manage-clips]
verify_jwt = false

[functions.forgot-username]
verify_jwt = false

[functions.forgot-password]
verify_jwt = false

[functions.sports-scores]
verify_jwt = false

[functions.gif-search]
verify_jwt = false
